name: Run index.js and commit changes

on:
  schedule:
    - cron: "0 6 * * *"  # minden nap 08:00 CET nyári időben (UTC+2 -> 06:00 UTC)
  workflow_dispatch: {}

permissions:
  contents: write   # KELL a push-hoz a GITHUB_TOKEN-nel

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # hagyd így, kell a push-hoz

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (ha van lockfile)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          fi

      - name: Run script
        run: node index.js

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: automatic update from scheduled run [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
